const noop = string => string;

module.exports = {
	reset: noop,
	bold: noop,
	dim: noop,
	italic: noop,
	underline: noop,
	inverse: noop,
	hidden: noop,
	strikethrough: noop,
	overline: noop,

	black: noop,
	red: noop,
	green: noop,
	yellow: noop,
	blue: noop,
	magenta: noop,
	cyan: noop,
	white: noop,

	blackBright: noop,
	grey: noop,
	gray: noop,
	redBright: noop,
	greenBright: noop,
	yellowBright: noop,
	blueBright: noop,
	magentaBright: noop,
	cyanBright: noop,
	whiteBright: noop,

	bgBlack: noop,
	bgRed: noop,
	bgGreen: noop,
	bgYellow: noop,
	bgBlue: noop,
	bgMagenta: noop,
	bgCyan: noop,
	bgWhite: noop,

	bgBlackBright: noop,
	bgGrey: noop,
	bgGray: noop,
	bgRedBright: noop,
	bgGreenBright: noop,
	bgYellowBright: noop,
	bgBlueBright: noop,
	bgMagentaBright: noop,
	bgCyanBright: noop,
	bgWhiteBright: noop,
};
